In [1]:
import pandas as pd

region = pd.Series(["Toronto", "Montreal", "Vancouver", "Calgary", "Ottawa"])

region

0      Toronto
1     Montreal
2    Vancouver
3      Calgary
4       Ottawa
dtype: object

In [2]:
can_lang = pd.read_csv("data/can_lang.csv")
type(can_lang)

pandas.core.frame.DataFrame

A list is an ordered collection of values. To create a list, we put the contents of the list in between square brackets [], where each item of the list is separated by a comma. A list can contain values of different types. The example below contains six str entries

In [3]:
cities = ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Winnipeg"]
cities

['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa', 'Winnipeg']

In [4]:
# A list can directly be converted to a pandas Series
cities_series = pd.Series(cities)
cities_series

0      Toronto
1    Vancouver
2     Montreal
3      Calgary
4       Ottawa
5     Winnipeg
dtype: object

A dict, or dictionary, contains pairs of “keys” and “values.” You use a key to look up its corresponding value. 

Dictionaries are created using curly brackets {}. Each entry starts with the key on the left, followed by a colon symbol :, and then the value. 

A dictionary can have multiple key-value pairs, each separted by a comma. Keys can take a wide variety of types (int and str are commonly used), and values can take any type; the key-value pairs in a dictionary can all be of different types, too.

In the example below, we create a dictionary that has two keys: "cities" and "population". The values associated with each are lists.

In [5]:
population_in_2016 = {
  "cities": ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Winnipeg"],
  "population": [2235145, 1027613, 1823281, 544870, 571146, 321484]
}
population_in_2016

{'cities': ['Toronto',
  'Vancouver',
  'Montreal',
  'Calgary',
  'Ottawa',
  'Winnipeg'],
 'population': [2235145, 1027613, 1823281, 544870, 571146, 321484]}

A dictionary can be converted to a data frame. Keys become the column names, and the values become the entries in those columns. 

Dictionaries on their own are quite simple objects; it is preferable to work with a data frame because then we have access to the built-in functionality in pandas (e.g. loc[], [], and many functions)

In [6]:
population_in_2016_df = pd.DataFrame(population_in_2016)
population_in_2016_df

      cities  population
0    Toronto     2235145
1  Vancouver     1027613
2   Montreal     1823281
3    Calgary      544870
4     Ottawa      571146
5   Winnipeg      321484

In [7]:
# there is no need to name the dictionary separately before passing it to pd.DataFrame; 
# we can instead construct the dictionary right inside the call. 
# This is often the most convenient way to create a new data frame.

population_in_2016_df = pd.DataFrame({
  "cities": ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Winnipeg"],
  "population": [2235145, 1027613, 1823281, 544870, 571146, 321484]
})
population_in_2016_df

      cities  population
0    Toronto     2235145
1  Vancouver     1027613
2   Montreal     1823281
3    Calgary      544870
4     Ottawa      571146
5   Winnipeg      321484

A tidy data frame satisfies the following three criteria:

1. Each row is a single observation
2. Each column is a single variable, and
3. Each value is a single cell (i.e., its entry in the data frame is not shared with another value).

In [8]:
lang_wide = pd.read_csv("data/region_lang_top5_cities_wide.csv")
lang_wide

,category,language,Toronto,Montréal,Vancouver,Calgary,Edmonton
0,Aboriginal languages,"Aboriginal languages, n.o.s.",80,30,70,20,25
1,Non-Official & Non-Aboriginal languages,Afrikaans,985,90,1435,960,575
2,Non-Official & Non-Aboriginal languages,"Afro-Asiatic languages, n.i.e.",360,240,45,45,65
3,Non-Official & Non-Aboriginal languages,Akan (Twi),8485,1015,400,705,885
4,Non-Official & Non-Aboriginal languages,Albanian,13260,2450,1090,1365,770
5,Non-Official & Non-Aboriginal languages,Wolof,165,2440,30,120,130
6,Aboriginal languages,Woods Cree,5,0,20,10,155
7,Non-Official & Non-Aboriginal languages,Wu (Shanghainese),5290,1025,4330,380,235
8,Non-Official & Non-Aboriginal languages,Yiddish,3355,8960,220,80,55
9,Non-Official & Non-Aboriginal languages,Yoruba,3380,210,190,1430,700

We use melt to combine the Toronto, Montréal, Vancouver, Calgary, and Edmonton columns into a single column called region, and create a column called mother_tongue that contains the count of how many Canadians report each language as their mother tongue for each metropolitan area

Data Frame Object = lang_wide #data frame object we want to reshape

id_vars = ["category", "language"] # columns can be used as idetifier variables

var_name = "region" # name of the new column to be created whose values will come from the [name of the columns] that we want to combine

value_name = "mother_tongue" # name of the new column to be created whose values come from the [values of the columns] that we wan to combine

In [9]:
lang_mother_tidy = lang_wide.melt(
    id_vars = ["category", "language"],
    var_name = "region",
    value_name = "mother_tongue"
)

lang_mother_tidy

,category,language,region,mother_tongue
0,Aboriginal languages,"Aboriginal languages, n.o.s.",Toronto,80
1,Non-Official & Non-Aboriginal languages,Afrikaans,Toronto,985
2,Non-Official & Non-Aboriginal languages,"Afro-Asiatic languages, n.i.e.",Toronto,360
3,Non-Official & Non-Aboriginal languages,Akan (Twi),Toronto,8485
4,Non-Official & Non-Aboriginal languages,Albanian,Toronto,13260
5,Non-Official & Non-Aboriginal languages,Wolof,Toronto,165
6,Aboriginal languages,Woods Cree,Toronto,5
7,Non-Official & Non-Aboriginal languages,Wu (Shanghainese),Toronto,5290
8,Non-Official & Non-Aboriginal languages,Yiddish,Toronto,3355
9,Non-Official & Non-Aboriginal languages,Yoruba,Toronto,3380
10,Aboriginal languages,"Aboriginal languages, n.o.s.",Montréal,30
11,Non-Official & Non-Aboriginal languages,Afrikaans,Montréal,90
12,Non-Official & Non-Aboriginal languages,"Afro-Asiatic languages, n.i.e.",Montréal,240
13,Non-Official & Non-Aboriginal languages,Akan (Twi),Montréal,1015
14,Non-Official & Non-Aboriginal languages,Albanian,Montréal,2450
15,Non-Official & Non-Aboriginal languages,Wolof,Montréal,2440
16,Aboriginal languages,Woods Cree,Montréal,0
17,Non-Official & Non-Aboriginal languages,Wu (Shanghainese),Montréal,1025
18,Non-Official & Non-Aboriginal languages,Yiddish,Montréal,8960
19,Non-Official & Non-Aboriginal languages,Yoruba,Montréal,210
20,Aboriginal languages,"Aboriginal languages, n.o.s.",Vancouver,70
21,Non-Official & Non-Aboriginal languages,Afrikaans,Vancouver,1435
22,Non-Official & Non-Aboriginal languages,"Afro-Asiatic languages, n.i.e.",Vancouver,45
23,Non-Official & Non-Aboriginal languages,Akan (Twi),Vancouver,400
24,Non-Official & Non-Aboriginal languages,Albanian,Vancouver,1090
25,Non-Official & Non-Aboriginal languages,Wolof,Vancouver,30
26,Aboriginal languages,Woods Cree,Vancouver,20
27,Non-Official & Non-Aboriginal languages,Wu (Shanghainese),Vancouver,4330
28,Non-Official & Non-Aboriginal languages,Yiddish,Vancouver,220
29,Non-Official & Non-Aboriginal languages,Yoruba,Vancouver,190
30,Aboriginal languages,"Aboriginal languages, n.o.s.",Calgary,20
31,Non-Official & Non-Aboriginal languages,Afrikaans,Calgary,960
32,Non-Official & Non-Aboriginal languages,"Afro-Asiatic languages, n.i.e.",Calgary,45
33,Non-Official & Non-Aboriginal languages,Akan (Twi),Calgary,705
34,Non-Official & Non-Aboriginal languages,Albanian,Calgary,1365
35,Non-Official & Non-Aboriginal languages,Wolof,Calgary,120
36,Aboriginal languages,Woods Cree,Calgary,10
37,Non-Official & Non-Aboriginal languages,Wu (Shanghainese),Calgary,380
38,Non-Official & Non-Aboriginal languages,Yiddish,Calgary,80
39,Non-Official & Non-Aboriginal languages,Yoruba,Calgary,1430
40,Aboriginal languages,"Aboriginal languages, n.o.s.",Edmonton,25
41,Non-Official & Non-Aboriginal languages,Afrikaans,Edmonton,575
42,Non-Official & Non-Aboriginal languages,"Afro-Asiatic languages, n.i.e.",Edmonton,65
43,Non-Official & Non-Aboriginal languages,Akan (Twi),Edmonton,885
44,Non-Official & Non-Aboriginal languages,Albanian,Edmonton,770
45,Non-Official & Non-Aboriginal languages,Wolof,Edmonton,130
46,Aboriginal languages,Woods Cree,Edmonton,155
47,Non-Official & Non-Aboriginal languages,Wu (Shanghainese),Edmonton,235
48,Non-Official & Non-Aboriginal languages,Yiddish,Edmonton,55
49,Non-Official & Non-Aboriginal languages,Yoruba,Edmonton,700

The data above is now tidy because all three criteria for tidy data have now been met:

All the variables (category, language, region and mother_tongue) are now their own columns in the data frame.

Each observation, i.e., each category, language, region, and count of Canadians where that language is the mother tongue, are in a single row.

Each value is a single cell, i.e., its row, column position in the data frame is not shared with another value.